services:
    server:
        build:
            context: ./server
            dockerfile: Dockerfile
        ports:
            - "5000:5000"
        volumes:
            - ./server/src:/usr/src/app/src
        depends_on:
            - database
        env_file:
            - .env

    database:
        image: postgres:16
        ports:
            - "5433:5432"
        environment:
            - POSTGRES_DB=${DATABASE}
            - POSTGRES_USER=${DATABASE_USERNAME}
            - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
        volumes:
            - pgdata:/var/lib/postgresql/data

    seeder:
        build:
            context: ./server
            dockerfile: Dockerfile
        depends_on:
            - database
        env_file:
            - .env
        command: npm run seed

volumes:
    pgdata:
