services:
  server:
    image: ghcr.io/denyshlushchenko/collabify/backend:latest
    container_name: collabify-backend
    ports:
      - "5000:5000"
    env_file: .env.docker

    restart: unless-stopped
